#!/usr/bin/env python
import sys

import rospy

from robot_scene.machine import ModelMeshSync


class MachinetalkSceneSync:
    def __init__(self):
        # Start ROS node
        rospy.init_node('machine_scene_sync')
        rospy.loginfo("Initializing Machinetalk scene sync")

        machine_urdfs = rospy.get_param('~machine_urdfs', {})
        update_interval_s = rospy.get_param('~update_interval_s', 1.0)

        self._model_sync = ModelMeshSync(
            update_interval_s=update_interval_s, machine_urdfs=machine_urdfs
        )

    def start(self):
        rospy.loginfo("Machinetalk scene sync node starting")
        rospy.on_shutdown(self.stop)
        self._model_sync.start()

    def stop(self):
        rospy.loginfo("Machinetalk scene sync node stopping")
        self._model_sync.stop()


def main():
    sync_node = MachinetalkSceneSync()

    sync_node.start()
    rospy.spin()

    sys.exit(0)


if __name__ == '__main__':
    main()
