#!/usr/bin/env python
import sys

import rospy

from robot_scene.tool import ToolMeshSync


class ToolSceneSync:
    def __init__(self):
        rospy.init_node('tool_scene_sync')
        rospy.loginfo("Initializing tool scene sync")

        tool_urdfs = rospy.get_param('~tool_urdfs', {})
        tool_attach_link = rospy.get_param('~tool_attach_link', 'flange')
        tool_touch_links = rospy.get_param('~tool_touch_links', ['link_6'])
        update_interval_s = rospy.get_param('~update_interval_s', 1.0)

        self._model_sync = ToolMeshSync(
            update_interval_s=update_interval_s,
            tool_urdfs=tool_urdfs,
            tool_attach_link=tool_attach_link,
            tool_touch_links=tool_touch_links,
        )

    def start(self):
        rospy.loginfo("tool scene sync node starting")
        rospy.on_shutdown(self.stop)
        self._model_sync.start()

    def stop(self):
        rospy.loginfo("tool scene sync node stopping")
        self._model_sync.stop()


def main():
    sync_node = ToolSceneSync()

    sync_node.start()
    rospy.spin()

    sys.exit(0)


if __name__ == '__main__':
    main()
