#!/usr/bin/env python3

import logging
import rospy
import time

import rosgraph.roslogging as _rl
import rospy.impl.rosout as _ro

from socket import error as _socket_error
from rosgraph import Master
import rosnode

import se_jogger.shuttle_jogger as shuttle_jogger

logging.getLogger("se_jogger").setLevel(logging.DEBUG)
logging.getLogger("se_jogger").addHandler(_rl.RosStreamHandler())
logging.getLogger("se_jogger").addHandler(_ro.RosOutHandler())


def _check_master():
    try:
        Master("/rostopic").getPid()
        return True
    except _socket_error:
        return False


def _ensure_master(wait=1):
    _tries = 0
    while _tries < wait:
        if _check_master():
            return True
        time.sleep(1)
        _tries += 1
    return False


class TormachJoggerNode:
    NODE_NAME = "tormach_se_jogger"

    def __init__(self):
        rospy.init_node(self.NODE_NAME, log_level=rospy.INFO)
        self._shuttle_jogger = shuttle_jogger.TormachShuttleExpressJogger()
        self._error_occured = False
        self._shuttle_jogger.add_error_observer(self.on_exit_requested)

    def __enter__(self):
        self._shuttle_jogger.start()
        return self

    def __exit__(self, exc_type, exc_val, traceback):
        self._shuttle_jogger.stop()

    @classmethod
    def check_running(cls):
        if f"/{cls.NODE_NAME}" in rosnode.get_node_names():
            return True
        return False

    @classmethod
    def imposible_to_connect(cls) -> bool:
        return not shuttle_jogger.TormachShuttleExpressJogger.can_open()

    def on_exit_requested(self, reason):
        self._error_occured = True
        #rospy.signal_shutdown(reason)

    def spin(self):
        rospy.spin()


def main():
    rospy.loginfo("Starting the Tormach Jogger node")
    if _ensure_master(10):
        if TormachJoggerNode.check_running():
            rospy.logwarn(
                "Launch of Tormach SE jogger node requested, "
                "but it is already running!"
            )
        while(not rospy.is_shutdown()):
            if TormachJoggerNode.imposible_to_connect():
                rospy.sleep(10)
                rospy.loginfo("Impossible to connect to the Tormach SE Jogger device")
                continue
            try:
                with TormachJoggerNode() as node:
                    while (not node._error_occured):
                        rospy.rostime.wallsleep(0.5)
            except Exception as e:
                rospy.logwarn(f"Error happened while running the Tormach SE Jogger device.\n {e}")
    # ROS master is not running
    # Should be signaled somehow


if __name__ == "__main__":
    main()
