"""
    PathPilot HUB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: pathpilot@tormach.com
    Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from ..configuration import Configuration


class File:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'fullpath': 'str',
        'type': 'str',
        'size': 'int',
        'mtime_utc': 'str',
        'children': 'list[File]',
    }

    attribute_map = {
        'name': 'name',
        'fullpath': 'fullpath',
        'type': 'type',
        'size': 'size',
        'mtime_utc': 'mtime_utc',
        'children': 'children',
    }

    def __init__(
        self,
        name=None,
        fullpath=None,
        type=None,
        size=None,
        mtime_utc=None,
        children=None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """File - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._fullpath = None
        self._type = None
        self._size = None
        self._mtime_utc = None
        self._children = None
        self.discriminator = None

        self.name = name
        if fullpath is not None:
            self.fullpath = fullpath
        self.type = type
        if size is not None:
            self.size = size
        if mtime_utc is not None:
            self.mtime_utc = mtime_utc
        if children is not None:
            self.children = children

    @property
    def name(self):
        """Gets the name of this File.  # noqa: E501

        name of the file or directory (no path portion)  # noqa: E501

        :return: The name of this File.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this File.

        name of the file or directory (no path portion)  # noqa: E501

        :param name: The name of this File.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and name is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501

        self._name = name

    @property
    def fullpath(self):
        """Gets the fullpath of this File.  # noqa: E501

        Path to the file (Relative to the API, not a disk path)  # noqa: E501

        :return: The fullpath of this File.  # noqa: E501
        :rtype: str
        """
        return self._fullpath

    @fullpath.setter
    def fullpath(self, fullpath):
        """Sets the fullpath of this File.

        Path to the file (Relative to the API, not a disk path)  # noqa: E501

        :param fullpath: The fullpath of this File.  # noqa: E501
        :type: str
        """

        self._fullpath = fullpath

    @property
    def type(self):
        """Gets the type of this File.  # noqa: E501

        f for file, d for directory  # noqa: E501

        :return: The type of this File.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this File.

        f for file, d for directory  # noqa: E501

        :param type: The type of this File.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and type is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `type`, must not be `None`"
            )  # noqa: E501

        self._type = type

    @property
    def size(self):
        """Gets the size of this File.  # noqa: E501

        size of file in bytes (omitted for directories)  # noqa: E501

        :return: The size of this File.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this File.

        size of file in bytes (omitted for directories)  # noqa: E501

        :param size: The size of this File.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def mtime_utc(self):
        """Gets the mtime_utc of this File.  # noqa: E501

        last modified time in utc yyyy-mm-dd hh:mm:ss.fractions  # noqa: E501

        :return: The mtime_utc of this File.  # noqa: E501
        :rtype: str
        """
        return self._mtime_utc

    @mtime_utc.setter
    def mtime_utc(self, mtime_utc):
        """Sets the mtime_utc of this File.

        last modified time in utc yyyy-mm-dd hh:mm:ss.fractions  # noqa: E501

        :param mtime_utc: The mtime_utc of this File.  # noqa: E501
        :type: str
        """

        self._mtime_utc = mtime_utc

    @property
    def children(self):
        """Gets the children of this File.  # noqa: E501

        children of this directory (omitted for files)  # noqa: E501

        :return: The children of this File.  # noqa: E501
        :rtype: list[File]
        """
        return self._children

    @children.setter
    def children(self, children):
        """Sets the children of this File.

        children of this directory (omitted for files)  # noqa: E501

        :param children: The children of this File.  # noqa: E501
        :type: list[File]
        """

        self._children = children

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(
                        lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                        value,
                    )
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict())
                            if hasattr(item[1], "to_dict")
                            else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, File):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, File):
            return True

        return self.to_dict() != other.to_dict()
