"""
    PathPilot HUB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: pathpilot@tormach.com
    Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from ..configuration import Configuration


class Group:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {'group_id': 'int', 'name': 'str', 'group_type': 'str'}

    attribute_map = {
        'group_id': 'group_id',
        'name': 'name',
        'group_type': 'group_type',
    }

    def __init__(
        self,
        group_id=None,
        name=None,
        group_type=None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """Group - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._group_id = None
        self._name = None
        self._group_type = None
        self.discriminator = None

        self.group_id = group_id
        self.name = name
        self.group_type = group_type

    @property
    def group_id(self):
        """Gets the group_id of this Group.  # noqa: E501

        id of the group in the database  # noqa: E501

        :return: The group_id of this Group.  # noqa: E501
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this Group.

        id of the group in the database  # noqa: E501

        :param group_id: The group_id of this Group.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and group_id is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `group_id`, must not be `None`"
            )  # noqa: E501

        self._group_id = group_id

    @property
    def name(self):
        """Gets the name of this Group.  # noqa: E501

        name of group or classroom  # noqa: E501

        :return: The name of this Group.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Group.

        name of group or classroom  # noqa: E501

        :param name: The name of this Group.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and name is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501

        self._name = name

    @property
    def group_type(self):
        """Gets the group_type of this Group.  # noqa: E501

        The type of the group  # noqa: E501

        :return: The group_type of this Group.  # noqa: E501
        :rtype: str
        """
        return self._group_type

    @group_type.setter
    def group_type(self, group_type):
        """Sets the group_type of this Group.

        The type of the group  # noqa: E501

        :param group_type: The group_type of this Group.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and group_type is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `group_type`, must not be `None`"
            )  # noqa: E501

        self._group_type = group_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(
                        lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                        value,
                    )
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict())
                            if hasattr(item[1], "to_dict")
                            else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Group):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Group):
            return True

        return self.to_dict() != other.to_dict()
