"""
    PathPilot HUB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: pathpilot@tormach.com
    Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from ..configuration import Configuration


class Listing:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'token': 'str',
        'email': 'str',
        'storage_used': 'int',
        'storage_avail': 'int',
        'contents': 'list[File]',
    }

    attribute_map = {
        'token': 'token',
        'email': 'email',
        'storage_used': 'storage_used',
        'storage_avail': 'storage_avail',
        'contents': 'contents',
    }

    def __init__(
        self,
        token=None,
        email=None,
        storage_used=None,
        storage_avail=None,
        contents=None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """Listing - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._token = None
        self._email = None
        self._storage_used = None
        self._storage_avail = None
        self._contents = None
        self.discriminator = None

        self.token = token
        self.email = email
        self.storage_used = storage_used
        self.storage_avail = storage_avail
        self.contents = contents

    @property
    def token(self):
        """Gets the token of this Listing.  # noqa: E501

        authorization token  # noqa: E501

        :return: The token of this Listing.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this Listing.

        authorization token  # noqa: E501

        :param token: The token of this Listing.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and token is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `token`, must not be `None`"
            )  # noqa: E501

        self._token = token

    @property
    def email(self):
        """Gets the email of this Listing.  # noqa: E501

        email associated with token  # noqa: E501

        :return: The email of this Listing.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Listing.

        email associated with token  # noqa: E501

        :param email: The email of this Listing.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and email is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `email`, must not be `None`"
            )  # noqa: E501

        self._email = email

    @property
    def storage_used(self):
        """Gets the storage_used of this Listing.  # noqa: E501

        total number of bytes used in this listing  # noqa: E501

        :return: The storage_used of this Listing.  # noqa: E501
        :rtype: int
        """
        return self._storage_used

    @storage_used.setter
    def storage_used(self, storage_used):
        """Sets the storage_used of this Listing.

        total number of bytes used in this listing  # noqa: E501

        :param storage_used: The storage_used of this Listing.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and storage_used is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `storage_used`, must not be `None`"
            )  # noqa: E501

        self._storage_used = storage_used

    @property
    def storage_avail(self):
        """Gets the storage_avail of this Listing.  # noqa: E501

        total number of bytes available for this account  # noqa: E501

        :return: The storage_avail of this Listing.  # noqa: E501
        :rtype: int
        """
        return self._storage_avail

    @storage_avail.setter
    def storage_avail(self, storage_avail):
        """Sets the storage_avail of this Listing.

        total number of bytes available for this account  # noqa: E501

        :param storage_avail: The storage_avail of this Listing.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and storage_avail is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `storage_avail`, must not be `None`"
            )  # noqa: E501

        self._storage_avail = storage_avail

    @property
    def contents(self):
        """Gets the contents of this Listing.  # noqa: E501

        files and directories for the account correlated with the authorization token  # noqa: E501

        :return: The contents of this Listing.  # noqa: E501
        :rtype: list[File]
        """
        return self._contents

    @contents.setter
    def contents(self, contents):
        """Sets the contents of this Listing.

        files and directories for the account correlated with the authorization token  # noqa: E501

        :param contents: The contents of this Listing.  # noqa: E501
        :type: list[File]
        """
        if (
            self.local_vars_configuration.client_side_validation
            and contents is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `contents`, must not be `None`"
            )  # noqa: E501

        self._contents = contents

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(
                        lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                        value,
                    )
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict())
                            if hasattr(item[1], "to_dict")
                            else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Listing):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Listing):
            return True

        return self.to_dict() != other.to_dict()
