"""
    PathPilot HUB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: pathpilot@tormach.com
    Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from ..configuration import Configuration


class Machine:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'guid': 'str',
        'sn': 'str',
        'model': 'str',
        'machineclass': 'str',
        'lic': 'int',
        'ppversion': 'str',
    }

    attribute_map = {
        'guid': 'guid',
        'sn': 'sn',
        'model': 'model',
        'machineclass': 'machineclass',
        'lic': 'lic',
        'ppversion': 'ppversion',
    }

    def __init__(
        self,
        guid=None,
        sn=None,
        model=None,
        machineclass=None,
        lic=None,
        ppversion=None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """Machine - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._guid = None
        self._sn = None
        self._model = None
        self._machineclass = None
        self._lic = None
        self._ppversion = None
        self.discriminator = None

        self.guid = guid
        if sn is not None:
            self.sn = sn
        self.model = model
        self.machineclass = machineclass
        self.lic = lic
        self.ppversion = ppversion

    @property
    def guid(self):
        """Gets the guid of this Machine.  # noqa: E501

        machine identifier  # noqa: E501

        :return: The guid of this Machine.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this Machine.

        machine identifier  # noqa: E501

        :param guid: The guid of this Machine.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and guid is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `guid`, must not be `None`"
            )  # noqa: E501

        self._guid = guid

    @property
    def sn(self):
        """Gets the sn of this Machine.  # noqa: E501

        serial number of machine  # noqa: E501

        :return: The sn of this Machine.  # noqa: E501
        :rtype: str
        """
        return self._sn

    @sn.setter
    def sn(self, sn):
        """Sets the sn of this Machine.

        serial number of machine  # noqa: E501

        :param sn: The sn of this Machine.  # noqa: E501
        :type: str
        """

        self._sn = sn

    @property
    def model(self):
        """Gets the model of this Machine.  # noqa: E501

        model of machine  # noqa: E501

        :return: The model of this Machine.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this Machine.

        model of machine  # noqa: E501

        :param model: The model of this Machine.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and model is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `model`, must not be `None`"
            )  # noqa: E501

        self._model = model

    @property
    def machineclass(self):
        """Gets the machineclass of this Machine.  # noqa: E501

        class of machine (e.g. mill, lathe, router)  # noqa: E501

        :return: The machineclass of this Machine.  # noqa: E501
        :rtype: str
        """
        return self._machineclass

    @machineclass.setter
    def machineclass(self, machineclass):
        """Sets the machineclass of this Machine.

        class of machine (e.g. mill, lathe, router)  # noqa: E501

        :param machineclass: The machineclass of this Machine.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and machineclass is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `machineclass`, must not be `None`"
            )  # noqa: E501

        self._machineclass = machineclass

    @property
    def lic(self):
        """Gets the lic of this Machine.  # noqa: E501

        license type  # noqa: E501

        :return: The lic of this Machine.  # noqa: E501
        :rtype: int
        """
        return self._lic

    @lic.setter
    def lic(self, lic):
        """Sets the lic of this Machine.

        license type  # noqa: E501

        :param lic: The lic of this Machine.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation and lic is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `lic`, must not be `None`"
            )  # noqa: E501

        self._lic = lic

    @property
    def ppversion(self):
        """Gets the ppversion of this Machine.  # noqa: E501

        pathpilot version number (without v prefix)  # noqa: E501

        :return: The ppversion of this Machine.  # noqa: E501
        :rtype: str
        """
        return self._ppversion

    @ppversion.setter
    def ppversion(self, ppversion):
        """Sets the ppversion of this Machine.

        pathpilot version number (without v prefix)  # noqa: E501

        :param ppversion: The ppversion of this Machine.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and ppversion is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `ppversion`, must not be `None`"
            )  # noqa: E501

        self._ppversion = ppversion

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(
                        lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                        value,
                    )
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict())
                            if hasattr(item[1], "to_dict")
                            else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Machine):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Machine):
            return True

        return self.to_dict() != other.to_dict()
