"""
    PathPilot HUB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: pathpilot@tormach.com
    Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from ..configuration import Configuration


class PutFilesBody:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {'overwrite': 'bool', 'filedata': 'file'}

    attribute_map = {'overwrite': 'overwrite', 'filedata': 'filedata'}

    def __init__(
        self, overwrite=None, filedata=None, local_vars_configuration=None
    ):  # noqa: E501
        """PutFilesBody - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._overwrite = None
        self._filedata = None
        self.discriminator = None

        if overwrite is not None:
            self.overwrite = overwrite
        if filedata is not None:
            self.filedata = filedata

    @property
    def overwrite(self):
        """Gets the overwrite of this PutFilesBody.  # noqa: E501

        overwrite existing file if present?  # noqa: E501

        :return: The overwrite of this PutFilesBody.  # noqa: E501
        :rtype: bool
        """
        return self._overwrite

    @overwrite.setter
    def overwrite(self, overwrite):
        """Sets the overwrite of this PutFilesBody.

        overwrite existing file if present?  # noqa: E501

        :param overwrite: The overwrite of this PutFilesBody.  # noqa: E501
        :type: bool
        """

        self._overwrite = overwrite

    @property
    def filedata(self):
        """Gets the filedata of this PutFilesBody.  # noqa: E501

        contents of the file (the actual bytes)  # noqa: E501

        :return: The filedata of this PutFilesBody.  # noqa: E501
        :rtype: file
        """
        return self._filedata

    @filedata.setter
    def filedata(self, filedata):
        """Sets the filedata of this PutFilesBody.

        contents of the file (the actual bytes)  # noqa: E501

        :param filedata: The filedata of this PutFilesBody.  # noqa: E501
        :type: file
        """

        self._filedata = filedata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(
                        lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                        value,
                    )
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict())
                            if hasattr(item[1], "to_dict")
                            else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PutFilesBody):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PutFilesBody):
            return True

        return self.to_dict() != other.to_dict()
