<?xml version="1.0"?>
<package format="2">
  <name>movej_ik_server</name>
  <version>0.0.3</version>

  <description>Enables deterministic joint goals for TRPL movej(p[]) motion</description>
  <maintainer email="jkaminski@tormach.com">Jakub Kaminski</maintainer>
  <author email="jkaminski@tormach.com">Jakub Kaminski</author>
  <license>BSD 3-Clause</license>
  <url type="website">TODO</url>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>moveit_ros_move_group</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>moveit_core</depend>
  <depend>roscpp</depend>
  <depend>rosparam_shortcuts</depend>
  <depend>sensor_msgs</depend>
  <depend>movej_ik_server_msgs</depend>
  <depend>tf</depend>
  <depend>tf_conversions</depend>
  <depend>geometry_msgs</depend> <!-- Added geometry_msgs as a dependency -->
  <build_depend>eigen</build_depend> <!-- Added Eigen as a build_depend -->
  <build_depend>std_msgs</build_depend>
  <build_depend>message_generation</build_depend>
  <depend>tf2</depend>
  <depend>tf2_kdl</depend>
  <depend>opw_kinematics</depend>
  <build_export_depend>std_msgs</build_export_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>rospy</exec_depend>

  <test_depend>rostest</test_depend>

</package>
