<?xml version="1.0"?>
<package format="2">
  <name>robot_scene</name>
  <version>0.1.0</version>
  <description>Syncs objects into the robot's planning scene.</description>

  <maintainer email="alex@machinekoder.com">Alexander Rössler</maintainer>
  <license>BSD</license>
  <!-- <url type="website">http://wiki.ros.org/ros_machinetalk</url> -->
  <author email="alex@machinekoder.com">Alexander Rössler</author>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>rospy</build_depend>

  <build_export_depend>rospy</build_export_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>urdfdom_py</exec_depend>
  <exec_depend>tf</exec_depend>
  <exec_depend>ros_machinetalk</exec_depend>
  <exec_depend>robot_frame</exec_depend>

  <test_depend>rostest</test_depend>
  <test_depend>ros_pytest</test_depend>

</package>
