"""
    PathPilot HUB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: pathpilot@tormach.com
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401

from ..api_client import ApiClient
from ..exceptions import ApiTypeError, ApiValueError  # noqa: F401


class DefaultApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete(self, fullpath, **kwargs):  # noqa: E501
        """Delete a file or a directory and all of its contents  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete(fullpath, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str fullpath: (required)
        :param int group_id: If included, get files for the group identified by group_id. If omitted, the logged in user's own personal storage is used. If param is included, group_type is also required
        :param str group_type: If included, get files for the group type indicated. group_id must also be specified.
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.delete_with_http_info(fullpath, **kwargs)  # noqa: E501

    def delete_with_http_info(self, fullpath, **kwargs):  # noqa: E501
        """Delete a file or a directory and all of its contents  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_with_http_info(fullpath, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str fullpath: (required)
        :param int group_id: If included, get files for the group identified by group_id. If omitted, the logged in user's own personal storage is used. If param is included, group_type is also required
        :param str group_type: If included, get files for the group type indicated. group_id must also be specified.
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['fullpath', 'group_id', 'group_type']
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
            ]
        )

        for key, val in local_var_params['kwargs'].items():
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'fullpath' is set
        if self.api_client.client_side_validation and (
            'fullpath' not in local_var_params
            or local_var_params['fullpath'] is None  # noqa: E501
        ):  # noqa: E501
            raise ApiValueError(
                "Missing the required parameter `fullpath` when calling `delete`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'fullpath' in local_var_params:
            path_params['fullpath'] = local_var_params['fullpath']  # noqa: E501

        query_params = []
        if (
            'group_id' in local_var_params
            and local_var_params['group_id'] is not None
        ):  # noqa: E501
            query_params.append(
                ('group_id', local_var_params['group_id'])
            )  # noqa: E501
        if (
            'group_type' in local_var_params
            and local_var_params['group_type'] is not None
        ):  # noqa: E501
            query_params.append(
                ('group_type', local_var_params['group_type'])
            )  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json']
        )  # noqa: E501

        # Authentication setting
        auth_settings = ['HubTokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/files/{fullpath}',
            'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get(
                '_return_http_data_only'
            ),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
        )

    def get_files(self, fullpath, **kwargs):  # noqa: E501
        """List directory contents or download a file  # noqa: E501

        If {fullpath} is a directory, return a full list of contents recursively for it.  If {fullpath} is a file, download the file.  For file downloads, the Range http header can be used to read just a small preview amount if desried.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_files(fullpath, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str fullpath: (required)
        :param bool stat: Flag for performing a file system 'stat' on {fullpath} regardless of whether it is a file or directory.  If omitted, false is assumed.  Handy for determining if a single hub path is a file or a directory, sizes, mtimes, etc.
        :param int group_id: If included, get files for the group identified by group_id. If omitted, the logged in user's own personal storage is used. If param is included, group_type is also required
        :param str group_type: If included, get files for the group type indicated. group_id must also be specified.
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: file
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.get_files_with_http_info(fullpath, **kwargs)  # noqa: E501

    def get_files_with_http_info(self, fullpath, **kwargs):  # noqa: E501
        """List directory contents or download a file  # noqa: E501

        If {fullpath} is a directory, return a full list of contents recursively for it.  If {fullpath} is a file, download the file.  For file downloads, the Range http header can be used to read just a small preview amount if desried.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_files_with_http_info(fullpath, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str fullpath: (required)
        :param bool stat: Flag for performing a file system 'stat' on {fullpath} regardless of whether it is a file or directory.  If omitted, false is assumed.  Handy for determining if a single hub path is a file or a directory, sizes, mtimes, etc.
        :param int group_id: If included, get files for the group identified by group_id. If omitted, the logged in user's own personal storage is used. If param is included, group_type is also required
        :param str group_type: If included, get files for the group type indicated. group_id must also be specified.
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(file, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['fullpath', 'stat', 'group_id', 'group_type']
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
            ]
        )

        for key, val in local_var_params['kwargs'].items():
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_files" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'fullpath' is set
        if self.api_client.client_side_validation and (
            'fullpath' not in local_var_params
            or local_var_params['fullpath'] is None  # noqa: E501
        ):  # noqa: E501
            raise ApiValueError(
                "Missing the required parameter `fullpath` when calling `get_files`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'fullpath' in local_var_params:
            path_params['fullpath'] = local_var_params['fullpath']  # noqa: E501

        query_params = []
        if (
            'stat' in local_var_params and local_var_params['stat'] is not None
        ):  # noqa: E501
            query_params.append(
                ('stat', local_var_params['stat'])
            )  # noqa: E501
        if (
            'group_id' in local_var_params
            and local_var_params['group_id'] is not None
        ):  # noqa: E501
            query_params.append(
                ('group_id', local_var_params['group_id'])
            )  # noqa: E501
        if (
            'group_type' in local_var_params
            and local_var_params['group_type'] is not None
        ):  # noqa: E501
            query_params.append(
                ('group_type', local_var_params['group_type'])
            )  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/*', 'application/json']
        )  # noqa: E501

        # Authentication setting
        auth_settings = ['HubTokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/files/{fullpath}',
            'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='file',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get(
                '_return_http_data_only'
            ),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
        )

    def get_groups(self, **kwargs):  # noqa: E501
        """List groups or classrooms that this user is part of  # noqa: E501

        Get a list of groups and their types for the current user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_groups(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: list[Group]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.get_groups_with_http_info(**kwargs)  # noqa: E501

    def get_groups_with_http_info(self, **kwargs):  # noqa: E501
        """List groups or classrooms that this user is part of  # noqa: E501

        Get a list of groups and their types for the current user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_groups_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(list[Group], status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = []
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
            ]
        )

        for key, val in local_var_params['kwargs'].items():
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_groups" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json']
        )  # noqa: E501

        # Authentication setting
        auth_settings = ['HubTokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/groups/',
            'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Group]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get(
                '_return_http_data_only'
            ),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
        )

    def get_license(self, machine, **kwargs):  # noqa: E501
        """Get license  # noqa: E501

        Get a license for a machine  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_license(machine, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param Machine machine: Machine details for license (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.get_license_with_http_info(machine, **kwargs)  # noqa: E501

    def get_license_with_http_info(self, machine, **kwargs):  # noqa: E501
        """Get license  # noqa: E501

        Get a license for a machine  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_license_with_http_info(machine, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param Machine machine: Machine details for license (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(str, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['machine']
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
            ]
        )

        for key, val in local_var_params['kwargs'].items():
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_license" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'machine' is set
        if self.api_client.client_side_validation and (
            'machine' not in local_var_params
            or local_var_params['machine'] is None  # noqa: E501
        ):  # noqa: E501
            raise ApiValueError(
                "Missing the required parameter `machine` when calling `get_license`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'machine' in local_var_params:
            body_params = local_var_params['machine']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json']
        )  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = (
            self.api_client.select_header_content_type(  # noqa: E501
                ['application/json']
            )
        )  # noqa: E501

        # Authentication setting
        auth_settings = ['HubTokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/machine/license',
            'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get(
                '_return_http_data_only'
            ),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
        )

    def get_token(self, email, password, **kwargs):  # noqa: E501
        """Get authentication token by providing credentials  # noqa: E501

        Long lived tokens are required on all other end point operations  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_token(email, password, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str email: email address for the HUB account (required)
        :param str password: password for the HUB account (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Token
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.get_token_with_http_info(
            email, password, **kwargs
        )  # noqa: E501

    def get_token_with_http_info(self, email, password, **kwargs):  # noqa: E501
        """Get authentication token by providing credentials  # noqa: E501

        Long lived tokens are required on all other end point operations  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_token_with_http_info(email, password, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str email: email address for the HUB account (required)
        :param str password: password for the HUB account (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(Token, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['email', 'password']
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
            ]
        )

        for key, val in local_var_params['kwargs'].items():
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_token" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'email' is set
        if self.api_client.client_side_validation and (
            'email' not in local_var_params
            or local_var_params['email'] is None  # noqa: E501
        ):  # noqa: E501
            raise ApiValueError(
                "Missing the required parameter `email` when calling `get_token`"
            )  # noqa: E501
        # verify the required parameter 'password' is set
        if self.api_client.client_side_validation and (
            'password' not in local_var_params
            or local_var_params['password'] is None  # noqa: E501
        ):  # noqa: E501
            raise ApiValueError(
                "Missing the required parameter `password` when calling `get_token`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'email' in local_var_params:
            form_params.append(
                ('email', local_var_params['email'])
            )  # noqa: E501
        if 'password' in local_var_params:
            form_params.append(
                ('password', local_var_params['password'])
            )  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json']
        )  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = (
            self.api_client.select_header_content_type(  # noqa: E501
                ['multipart/form-data']
            )
        )  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/token',
            'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Token',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get(
                '_return_http_data_only'
            ),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
        )

    def put_files(self, fullpath, **kwargs):  # noqa: E501
        """Upload a file or create a directory at the {fullpath} location  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_files(fullpath, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str fullpath: (required)
        :param bool dir: Flag for whether {fullpath} should be a directory or a file.  If ommitted, file is assumed.
        :param str mtime_utc: last modified time for file in UTC
        :param str atime_utc: last access time for file in UTC
        :param int group_id: If included, get files for the group identified by group_id. If omitted, the logged in user's own personal storage is used. If param is included, group_type is also required
        :param str group_type: If included, get files for the group type indicated. group_id must also be specified.
        :param bool overwrite: overwrite existing file if present?
        :param file filedata: contents of the file (the actual bytes)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.put_files_with_http_info(fullpath, **kwargs)  # noqa: E501

    def put_files_with_http_info(self, fullpath, **kwargs):  # noqa: E501
        """Upload a file or create a directory at the {fullpath} location  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_files_with_http_info(fullpath, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str fullpath: (required)
        :param bool dir: Flag for whether {fullpath} should be a directory or a file.  If ommitted, file is assumed.
        :param str mtime_utc: last modified time for file in UTC
        :param str atime_utc: last access time for file in UTC
        :param int group_id: If included, get files for the group identified by group_id. If omitted, the logged in user's own personal storage is used. If param is included, group_type is also required
        :param str group_type: If included, get files for the group type indicated. group_id must also be specified.
        :param bool overwrite: overwrite existing file if present?
        :param file filedata: contents of the file (the actual bytes)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'fullpath',
            'dir',
            'mtime_utc',
            'atime_utc',
            'group_id',
            'group_type',
            'overwrite',
            'filedata',
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
            ]
        )

        for key, val in local_var_params['kwargs'].items():
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method put_files" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'fullpath' is set
        if self.api_client.client_side_validation and (
            'fullpath' not in local_var_params
            or local_var_params['fullpath'] is None  # noqa: E501
        ):  # noqa: E501
            raise ApiValueError(
                "Missing the required parameter `fullpath` when calling `put_files`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'fullpath' in local_var_params:
            path_params['fullpath'] = local_var_params['fullpath']  # noqa: E501

        query_params = []
        if (
            'dir' in local_var_params and local_var_params['dir'] is not None
        ):  # noqa: E501
            query_params.append(('dir', local_var_params['dir']))  # noqa: E501
        if (
            'mtime_utc' in local_var_params
            and local_var_params['mtime_utc'] is not None
        ):  # noqa: E501
            query_params.append(
                ('mtime_utc', local_var_params['mtime_utc'])
            )  # noqa: E501
        if (
            'atime_utc' in local_var_params
            and local_var_params['atime_utc'] is not None
        ):  # noqa: E501
            query_params.append(
                ('atime_utc', local_var_params['atime_utc'])
            )  # noqa: E501
        if (
            'group_id' in local_var_params
            and local_var_params['group_id'] is not None
        ):  # noqa: E501
            query_params.append(
                ('group_id', local_var_params['group_id'])
            )  # noqa: E501
        if (
            'group_type' in local_var_params
            and local_var_params['group_type'] is not None
        ):  # noqa: E501
            query_params.append(
                ('group_type', local_var_params['group_type'])
            )  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'overwrite' in local_var_params:
            form_params.append(
                ('overwrite', local_var_params['overwrite'])
            )  # noqa: E501
        if 'filedata' in local_var_params:
            local_var_files['filedata'] = local_var_params[
                'filedata'
            ]  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json']
        )  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = (
            self.api_client.select_header_content_type(  # noqa: E501
                ['multipart/form-data']
            )
        )  # noqa: E501

        # Authentication setting
        auth_settings = ['HubTokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/files/{fullpath}',
            'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get(
                '_return_http_data_only'
            ),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
        )

    def rename(self, fullpath, newname, **kwargs):  # noqa: E501
        """Rename the file or directory identified by {fullpath}  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.rename(fullpath, newname, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str fullpath: (required)
        :param str newname: New name for file or directory (no path portion) (required)
        :param int group_id: If included, get files for the group identified by group_id. If omitted, the logged in user's own personal storage is used. If param is included, group_type is also required
        :param str group_type: If included, get files for the group type indicated. group_id must also be specified.
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.rename_with_http_info(
            fullpath, newname, **kwargs
        )  # noqa: E501

    def rename_with_http_info(self, fullpath, newname, **kwargs):  # noqa: E501
        """Rename the file or directory identified by {fullpath}  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.rename_with_http_info(fullpath, newname, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str fullpath: (required)
        :param str newname: New name for file or directory (no path portion) (required)
        :param int group_id: If included, get files for the group identified by group_id. If omitted, the logged in user's own personal storage is used. If param is included, group_type is also required
        :param str group_type: If included, get files for the group type indicated. group_id must also be specified.
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['fullpath', 'newname', 'group_id', 'group_type']
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
            ]
        )

        for key, val in local_var_params['kwargs'].items():
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method rename" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'fullpath' is set
        if self.api_client.client_side_validation and (
            'fullpath' not in local_var_params
            or local_var_params['fullpath'] is None  # noqa: E501
        ):  # noqa: E501
            raise ApiValueError(
                "Missing the required parameter `fullpath` when calling `rename`"
            )  # noqa: E501
        # verify the required parameter 'newname' is set
        if self.api_client.client_side_validation and (
            'newname' not in local_var_params
            or local_var_params['newname'] is None  # noqa: E501
        ):  # noqa: E501
            raise ApiValueError(
                "Missing the required parameter `newname` when calling `rename`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'fullpath' in local_var_params:
            path_params['fullpath'] = local_var_params['fullpath']  # noqa: E501

        query_params = []
        if (
            'newname' in local_var_params
            and local_var_params['newname'] is not None
        ):  # noqa: E501
            query_params.append(
                ('newname', local_var_params['newname'])
            )  # noqa: E501
        if (
            'group_id' in local_var_params
            and local_var_params['group_id'] is not None
        ):  # noqa: E501
            query_params.append(
                ('group_id', local_var_params['group_id'])
            )  # noqa: E501
        if (
            'group_type' in local_var_params
            and local_var_params['group_type'] is not None
        ):  # noqa: E501
            query_params.append(
                ('group_type', local_var_params['group_type'])
            )  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json']
        )  # noqa: E501

        # Authentication setting
        auth_settings = ['HubTokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/files/{fullpath}',
            'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get(
                '_return_http_data_only'
            ),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
        )

    def revoke_token(self, **kwargs):  # noqa: E501
        """Revoke authentication token  # noqa: E501

        Revokes a long lived authentication token so it is no longer is valid for any end point operations  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.revoke_token(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Token
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.revoke_token_with_http_info(**kwargs)  # noqa: E501

    def revoke_token_with_http_info(self, **kwargs):  # noqa: E501
        """Revoke authentication token  # noqa: E501

        Revokes a long lived authentication token so it is no longer is valid for any end point operations  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.revoke_token_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(Token, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = []
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
            ]
        )

        for key, val in local_var_params['kwargs'].items():
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method revoke_token" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json']
        )  # noqa: E501

        # Authentication setting
        auth_settings = ['HubTokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/token',
            'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Token',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get(
                '_return_http_data_only'
            ),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
        )

    def update_machine_status(self, machine, **kwargs):  # noqa: E501
        """Provide machine status  # noqa: E501

        Periodically send status updates to HUB  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_machine_status(machine, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param Machine machine: Machine details for status (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.update_machine_status_with_http_info(
            machine, **kwargs
        )  # noqa: E501

    def update_machine_status_with_http_info(
        self, machine, **kwargs
    ):  # noqa: E501
        """Provide machine status  # noqa: E501

        Periodically send status updates to HUB  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_machine_status_with_http_info(machine, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param Machine machine: Machine details for status (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['machine']
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
            ]
        )

        for key, val in local_var_params['kwargs'].items():
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_machine_status" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'machine' is set
        if self.api_client.client_side_validation and (
            'machine' not in local_var_params
            or local_var_params['machine'] is None  # noqa: E501
        ):  # noqa: E501
            raise ApiValueError(
                "Missing the required parameter `machine` when calling `update_machine_status`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'machine' in local_var_params:
            body_params = local_var_params['machine']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json']
        )  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = (
            self.api_client.select_header_content_type(  # noqa: E501
                ['application/json']
            )
        )  # noqa: E501

        # Authentication setting
        auth_settings = ['HubTokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/machine/status',
            'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get(
                '_return_http_data_only'
            ),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
        )

    def upload_log_data(self, fullpath, guid, filedata, **kwargs):  # noqa: E501
        """Provide latest log data  # noqa: E501

        Upload log data for a machine  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.upload_log_data(fullpath, guid, filedata, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str fullpath: (required)
        :param str guid: machine identifier (required)
        :param file filedata: contents of the log data file (the actual bytes) (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.upload_log_data_with_http_info(
            fullpath, guid, filedata, **kwargs
        )  # noqa: E501

    def upload_log_data_with_http_info(
        self, fullpath, guid, filedata, **kwargs
    ):  # noqa: E501
        """Provide latest log data  # noqa: E501

        Upload log data for a machine  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.upload_log_data_with_http_info(fullpath, guid, filedata, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str fullpath: (required)
        :param str guid: machine identifier (required)
        :param file filedata: contents of the log data file (the actual bytes) (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['fullpath', 'guid', 'filedata']
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
            ]
        )

        for key, val in local_var_params['kwargs'].items():
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method upload_log_data" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'fullpath' is set
        if self.api_client.client_side_validation and (
            'fullpath' not in local_var_params
            or local_var_params['fullpath'] is None  # noqa: E501
        ):  # noqa: E501
            raise ApiValueError(
                "Missing the required parameter `fullpath` when calling `upload_log_data`"
            )  # noqa: E501
        # verify the required parameter 'guid' is set
        if self.api_client.client_side_validation and (
            'guid' not in local_var_params
            or local_var_params['guid'] is None  # noqa: E501
        ):  # noqa: E501
            raise ApiValueError(
                "Missing the required parameter `guid` when calling `upload_log_data`"
            )  # noqa: E501
        # verify the required parameter 'filedata' is set
        if self.api_client.client_side_validation and (
            'filedata' not in local_var_params
            or local_var_params['filedata'] is None  # noqa: E501
        ):  # noqa: E501
            raise ApiValueError(
                "Missing the required parameter `filedata` when calling `upload_log_data`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'fullpath' in local_var_params:
            path_params['fullpath'] = local_var_params['fullpath']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'guid' in local_var_params:
            form_params.append(('guid', local_var_params['guid']))  # noqa: E501
        if 'filedata' in local_var_params:
            local_var_files['filedata'] = local_var_params[
                'filedata'
            ]  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json']
        )  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = (
            self.api_client.select_header_content_type(  # noqa: E501
                ['multipart/form-data']
            )
        )  # noqa: E501

        # Authentication setting
        auth_settings = ['HubTokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/machine/logdata/{fullpath}',
            'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get(
                '_return_http_data_only'
            ),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
        )
