<?xml version="1.0"?>
<package format="2">
  <name>lidar_pointcloud_processor_msgs</name>
  <version>0.0.1</version>
  <description>Custom messages and services for LIDAR workpiece detection and processing</description>

  <maintainer email="your_email@example.com">Your Name</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>message_generation</depend>

  <build_depend>message_runtime</build_depend>
  <exec_depend>message_runtime</exec_depend>

  <export>
    <build_type>catkin</build_type>
  </export>
</package>
