#!/usr/bin/env python
import sys

import rospy
from ros_machinetalk.instance import InstanceServer


UPDATE_INTERVAL = 0.5
MACHINETALK_INSTANCES_TOPIC = 'machinetalk/instances'
MACHINETALK_NODES_PARAM = 'machinetalk/nodes'


class MachinetalkManagerNode:
    def __init__(self):
        # Start ROS node
        rospy.init_node("machinetalk_manager")
        rospy.loginfo("Initializing Machinetalk Manager node")

        self._server = InstanceServer()

    def start(self):
        rospy.loginfo('Machinetalk Manager node starting')
        rospy.on_shutdown(self.stop)
        self._server.start()

    def stop(self):
        rospy.loginfo('Machinetalk Manager node stopping')
        self._server.stop()


def main():
    manager = MachinetalkManagerNode()

    manager.start()
    rospy.spin()

    sys.exit(0)


if __name__ == '__main__':
    main()
