#!/usr/bin/env python
import rospy

from robot_frame import FramePublisher

NODE_NAME = 'frame_node'


class FrameNode:
    """Publishes work and tool frames."""

    def __init__(self):
        self._frame_pub = None

    def start(self):
        rospy.init_node(NODE_NAME)
        namespace = rospy.get_param('~namespace')
        publish_interval_s = float(
            rospy.get_param(
                '~publish_interval_s',
                FramePublisher.DEFAULT_PUBLISH_INTERVAL_S,
            )
        )
        pose_reference_frame = rospy.get_param('~pose_reference_frame', 'world')
        cache_tfs = rospy.get_param("~cache_tfs", False)
        self._frame_pub = FramePublisher(
            namespace, pose_reference_frame, publish_interval_s, cache_tfs
        )

    def stop(self):
        self._frame_pub.stop()


if __name__ == '__main__':
    node = FrameNode()
    node.start()
    rospy.spin()
    node.stop()
