<?xml version="1.0"?>
<package format="2">
  <name>cartesian_state</name>
  <version>0.0.3</version>

  <description>Converts joint states into cartesian positions.</description>
  <maintainer email="alex@machinekoder.com">Alexander Rössler</maintainer>
  <author email="alex@machinekoder.com">Alexander Rössler</author>
  <license>BSD 3-Clause</license>
  <url type="website">TODO</url>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>moveit_ros_move_group</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>roscpp</depend>
  <depend>rosparam_shortcuts</depend>
  <depend>sensor_msgs</depend>
  <depend>cartesian_state_msgs</depend>
  <depend>tf</depend>
  <depend>tf_conversions</depend>

  <test_depend>rostest</test_depend>

</package>
