#!/usr/bin/env python
import rospy
from robot_jog import JogFrameServer


class ContinuousJogFrameNode:
    """
    The continuous_jog_frame_node publishes planning and command frame for
    continuous jogging with moveit_servo.
    """

    NODE_NAME = 'continuous_jog_frame_node'

    def __init__(self):
        self._jog_frame_server = None

    def start(self):
        rospy.init_node(self.NODE_NAME)
        self._jog_frame_server = JogFrameServer()

    def spin(self):
        rospy.spin()

    def stop(self):
        self._jog_frame_server.stop()


if __name__ == '__main__':
    node = ContinuousJogFrameNode()
    node.start()
    node.spin()
    node.stop()
