#!/usr/bin/env python
import rospy
from robot_jog import InteractiveMoveServer


class InteractiveJogNode:
    """
    The interactive_jog_node exposes offset (step) and absolute jogging via MoveIt.
    """

    NODE_NAME = 'interactive_jog_node'

    def __init__(self):
        self._interactive_move = None

    def start(self):
        rospy.init_node(self.NODE_NAME)
        self._interactive_move = InteractiveMoveServer()

    def spin(self):
        rospy.spin()

    def stop(self):
        self._interactive_move.shutdown()


if __name__ == '__main__':
    node = InteractiveJogNode()
    node.start()
    node.spin()
    node.stop()
