#!/usr/bin/env python
import rospy
from pynput.keyboard import Key, Listener

from robot_jog import InteractiveMoveClient

NODE_NAME = 'simple_key_jog'


class SimpleKeyJog:
    """
    Very simple keyboard jogging implementation to the test-drive the jog_node
    """

    def __init__(self):
        self._client = None
        self._active = False

    def start(self):
        rospy.init_node(NODE_NAME)
        self._client = InteractiveMoveClient()

    def stop(self):
        self._client.stop()

    def spin(self):
        with Listener(
            on_press=self._on_press, on_release=self._on_release
        ) as listener:
            listener.join()

    def _on_press(self, key):
        if self._active:
            return

        switch = {
            Key.right: lambda: self._client.set_offset_pose_target(
                ['x'], [0.01]
            ),
            Key.left: lambda: self._client.set_offset_pose_target(
                ['x'], [-0.01]
            ),
            Key.up: lambda: self._client.set_offset_pose_target(['y'], [0.01]),
            Key.down: lambda: self._client.set_offset_pose_target(
                ['y'], [-0.01]
            ),
            Key.page_up: lambda: self._client.set_absolute_pose_target(
                ['x'], [0.0]
            ),
            Key.page_down: lambda: self._client.set_absolute_pose_target(
                ['y'], [0.0]
            ),
        }

        if key in switch:
            self._active = True
            _ = switch[key]()
            self._client.start()

    def _on_release(self, key):
        if key == Key.esc:
            return False
        elif key in (
            Key.right,
            Key.left,
            Key.up,
            Key.down,
            Key.page_up,
            Key.page_down,
        ):
            self._active = False
            self._client.stop()


if __name__ == '__main__':
    jog = SimpleKeyJog()
    jog.start()
    jog.spin()
    jog.stop()
