#!/usr/bin/env python

import sys
import os
import signal
import argparse
import traceback

from PySide6.QtCore import QTimer, QObject, QUrl, QLoggingCategory
from PySide6.QtWidgets import QApplication
from PySide6.QtQml import QQmlApplicationEngine
from PySide6.QtGui import QIcon

import rospy

from robot_ui.pathpilot.base import (
    MimeIconProvider,
    ToolTipImageProvider,
    Translator,
    recursively_register_types,
)
from robot_ui.pathpilot.base.resource_paths import ICON_PATH, TRANSLATIONS_PATH
from robot_ui.pathpilot.development.python_reloader import PythonReloader

# QML is installed in the same directory as the robot_ui top-level
# module
import robot_ui

SHUTDOWN_CHECK_INTERVAL_MS = 500


# see http://code.activestate.com/recipes/496735-workaround-for-missed-sigint-in-multithreaded-prog/
class SignalWatcher:
    """this class solves two problems with multithreaded
    programs in Python, (1) a signal might be delivered
    to any thread (which is just a malfeature) and (2) if
    the thread that gets the signal is waiting, the signal
    is ignored (which is a bug).

    The watcher is a concurrent process (not thread) that
    waits for a signal and the process that contains the
    threads.  See Appendix A of The Little Book of Semaphores.
    http://greenteapress.com/semaphores/

    I have only tested this on Linux.  I would expect it to
    work on the Macintosh and not work on Windows.
    """

    def __init__(self):
        """Creates a child thread, which returns.  The parent
        thread waits for a KeyboardInterrupt and then kills
        the child thread.
        """
        self.parent = os.getpid()
        self.child = os.fork()
        if self.child == 0:
            return
        else:
            self.watch()

    def watch(self):
        try:
            os.wait()
        except KeyboardInterrupt:
            self.kill()
        sys.exit()

    def kill(self):
        try:
            os.kill(self.child, signal.SIGTERM)
        except OSError:
            pass
        try:
            os.kill(self.parent, signal.SIGTERM)
        except OSError:
            pass


class SignalHandler:
    _signal_chain = {}

    def __init__(self):
        self._signal_chain[signal.SIGINT] = signal.signal(
            signal.SIGINT,
            lambda sig, stk: self._sig_handler(
                sig, stk, lambda *args: RobotGui.shutdown()
            ),
        )
        self._signal_chain[signal.SIGTERM] = signal.signal(
            signal.SIGTERM,
            lambda sig, stk: self._sig_handler(
                sig, stk, lambda *args: RobotGui.shutdown()
            ),
        )
        sys.excepthook = self._log_error

    @staticmethod
    def _sig_handler(sig, stackframe, function):
        function(sig, stackframe)
        prev_handler = SignalHandler._signal_chain.get(sig, None)
        if prev_handler is not None and not isinstance(prev_handler, int):
            try:
                prev_handler(sig, stackframe)
            except KeyboardInterrupt:
                pass  # filter out generic keyboard interrupt handler

    @staticmethod
    def _log_error(etype, evalue, etraceback):
        if etype is KeyboardInterrupt:
            SignalHandler._sig_handler(
                signal.SIGINT, None, lambda *args: RobotGui.shutdown()
            )
            return

        tb = ''.join(traceback.format_exception(etype, evalue, etraceback))
        rospy.logfatal(f"An unexpected error occurred:\n{evalue}\n\n{tb}\n")


class RobotGui(QObject):
    def __init__(self, args, parent=None):
        super().__init__(parent)
        self._signal_handler = SignalHandler()

        rospy.init_node('robot_ui')
        rospy.loginfo('starting robot ui node')
        self._create_program_directory()

        qml_main = os.path.join(
            'robot_ui', 'live.qml' if args.live else 'main.qml'
        )
        module_path = robot_ui.__path__[-1]
        for path in robot_ui.__path__:
            if os.path.exists(os.path.join(path, qml_main)):
                module_path = path
                break

        if module_path not in sys.path:
            sys.path.insert(0, module_path)

        recursively_register_types(module_path, ignore=['launcher_ui'])

        self._engine = QQmlApplicationEngine(
            self
        )  # set parent for proper cleanup
        self._engine.addImportPath(module_path)
        self._engine.rootContext().setContextProperty(
            'parsedArguments', vars(args)
        )
        self._translator = Translator(
            path=QUrl.fromLocalFile(TRANSLATIONS_PATH),
            name='pathpilot',
            engine=self._engine,
            parent=self,
        )
        self._engine.rootContext().setContextProperty(
            Translator.__name__, self._translator
        )
        if args.live:
            global reloader  # necessary to make reloading work, prevents garbage collection
            reloader = PythonReloader(main=__file__)
            self._engine.rootContext().setContextProperty(
                PythonReloader.__name__, reloader
            )
            self._engine.rootContext().setContextProperty(
                'userProjectPath',
                QUrl.fromLocalFile(os.path.join(module_path, '..')),
            )
        self._engine.rootContext().setContextProperty('devMode', args.dev_mode)
        self._engine.addImageProvider(
            'mimeIconProvider', MimeIconProvider(theme="oxygen")
        )
        self._engine.addImageProvider(
            'toolTipImageProvider', ToolTipImageProvider()
        )
        url = QUrl.fromLocalFile(os.path.join(module_path, qml_main))
        self._engine.objectCreated.connect(
            lambda obj, obj_url: self._exit_on_failure(obj, obj_url, url)
        )
        self._engine.load(url)

        self._start_check_timer()

    def __del__(self):
        self._engine.deleteLater()
        del self._engine

    @staticmethod
    def _exit_on_failure(obj: QObject, obj_url: QUrl, main_url: QUrl):
        if not obj and main_url == obj_url:
            QApplication.exit(-1)

    @staticmethod
    def _create_program_directory():
        path = os.path.expanduser(
            rospy.get_param('robot_ui_config/program_home_path')
        )
        if not os.path.isdir(path):
            os.makedirs(path)

    def _start_check_timer(self):
        self._timer = QTimer(self)
        self._timer.timeout.connect(self._check_continue)
        self._timer.start(SHUTDOWN_CHECK_INTERVAL_MS)

    def _check_continue(self):
        if rospy.is_shutdown():
            self._timer.stop()
            RobotGui.shutdown()

    @staticmethod
    def shutdown():
        QApplication.quit()


if __name__ == '__main__':
    SignalWatcher()
    parser = argparse.ArgumentParser(
        description="""
            PathPilot for ROS UI
            """
    )
    parser.add_argument(
        '-l',
        '--live',
        help='The live coding version of this application',
        action='store_true',
    )
    parser.add_argument(
        '-d',
        '--display-config',
        help='A display config file (.rviz) to load',
        type=str,
    )
    parser.add_argument(
        '-td',
        '--test-deployment',
        help='Pass this option if you just want to test the QML file deployment, exits immediately',
        action='store_true',
    )
    parser.add_argument(
        '--dev-mode', help='Start in development mode.', action='store_true'
    )
    arguments, unknown = parser.parse_known_args()

    QLoggingCategory.setFilterRules(
        'qt.svg.warning=false\nqt.qpa.xcb=false\n'
    )  # disable SVG loading warnings and XCB errors

    app = QApplication(sys.argv)
    app.setOrganizationName('Tormach')
    app.setOrganizationDomain('tormach.com')
    app.setApplicationName('PathPilot Robot Edition')
    gui = RobotGui(arguments)  # changes working directory
    app.setWindowIcon(
        QIcon(os.path.join(ICON_PATH, 'application/png/icon.png'))
    )
    ret = app.exec()
    del gui  # delete QmlEngine, fixes "cannot read property of null" errors
    sys.exit(ret)
