<?xml version="1.0"?>
<package format="2">
  <name>robot_frame</name>
  <version>0.1.0</version>
  <description>
    User frame and tool frame management for robot programs.
  </description>
  <maintainer email="alex@machinekoder.com">Alexander Rössler</maintainer>
  <license>TODO</license>

  <url>TODO</url>
  <author>Alexander Rössler</author>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>redis_store</depend>
  <depend>tf</depend>
  <depend>geometry_msgs</depend>
  <depend>robot_frame_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_geometry_msgs</depend>

  <test_depend>rostest</test_depend>
  <test_depend>ros_pytest</test_depend>
  <test_depend>python-pytest-dependency-pip</test_depend>

</package>
